### ISSUE TITLE
failed to create symbolic link 'buildkite-agent-latest.tar.gz': File exists

### ISSUE THREAD

**Issue by nicomfe** [buildkite/heroku-buildkite-agent#7]
I believe this is happening cause I had an old version of the agent installed and this is trying to install a new one. The error on my build is: 

```
-----> Buildkite Agent app detected
-----> Installing Buildkite Agent v2.6.9
ln: failed to create symbolic link 'buildkite-agent-latest.tar.gz': File exists
```

**Comment by bjeanes** [comment]
Does installing [this Heroku CLI plugin](https://github.com/heroku/heroku-repo) then running `heroku repo:purge_cache` fix the issue?

**Comment by nicomfe** [comment]
@bjeanes Getting an error when trying to install that plugin

```
heroku plugins:install heroku-repo
Running: /Users/nicofetter/.local/share/heroku/client/bin/heroku
Installing heroku-repo@latest... !
 ▸    yarn add heroku-repo@latest --non-interactive --mutex=file:/Users/nicofetter/.local/share/heroku/plugins/yarn.lock --preferred-cache-folder=/Users/nicofetter/Library/Caches/heroku/yarn --registry=https://cli-npm.heroku.com exited with code 1
 ▸    error An unexpected error occurred: "https://cli-npm.heroku.com/heroku-run: ETIMEDOUT".
 ▸    Error: https://cli-npm.heroku.com/mkdirp: ETIMEDOUT
 ▸    at Timeout._onTimeout (/Users/nicofetter/.local/share/heroku/client/node_modules/yarn/lib/cli.js:123749:19)
 ▸    at ontimeout (timers.js:458:11)
 ▸    at tryOnTimeout (timers.js:296:5)
 ▸    at Timer.listOnTimeout (timers.js:259:5)
 ▸
 ▸    yarn add v1.3.2
 ▸    [1/4] Resolving packages...
 ▸    info If you think this is a bug, please open a bug report with the information provided in "/Users/nicofetter/.local/share/heroku/plugins/yarn-error.log".
 ▸    info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by nicomfe** [comment]
I tried a couple of times and finally got installed. And running the command you suggested fixed the problem!. Thanks man!! @bjeanes
