### ISSUE TITLE
No longer seems to work since agent v3

### ISSUE THREAD

**Issue by phantomwhale** [buildkite/heroku-buildkite-agent#8]
Launching this repo into heroku now sets up an Agent v3.8.4, but when you try and run any pipeline command, it fails with:

⚠️ Your buildkite-agent.cfg file contains a deprecated bootstrap.sh 
  | As part of the upgrade from Agent v2 to v3, a bootstrap-script compatibility shim was added to your buildkite-agent.cfg.
  |  
  | To silence this warning, you can comment out the bootstrap-script line in /app/.buildkite/buildkite-agent.cfg.
  |  
  | For more information, see our Buildkite Agent 3.0 upgrade guide:
  | https://buildkite.com/docs/agent/upgrading-to-v3
  | /app/.buildkite/bootstrap.sh: 15: exec: buildkite-agent: not found

**Comment by toolmantim** [comment]
Hey @phantomwhale! 👋🏼 @bjeanes and Buildkite no longer maintain the Heroku agent much anymore, sorry you hit some bugs.

I've just made some quick fixes, and it should be working if you want to give it another go.

**Comment by phantomwhale** [comment]
Ok cool - I was just trying to find a quick and dirty way to get a build agent up without setting up AWS or similiar.

Tried the new version, but it seems to fail during the build step:

```
-----> SSH private key app detected
-----> No SSH private key
-----> github-netrc app detected
       Generated .netrc & .curlrc files (available only at build-time)
/app/tmp/buildpacks/8bb9ecda5c99fd5b4b98d8c21e7c582252df8a42bc85951aa17af25c483277acf11bfeb81ff44056582eddfffa3f24b54eaf67ea15b7c3b1940fbf87fb73e5f5/lib/github.rb:20:in `[]': no implicit conversion of String into Integer (TypeError)
	from /app/tmp/buildpacks/8bb9ecda5c99fd5b4b98d8c21e7c582252df8a42bc85951aa17af25c483277acf11bfeb81ff44056582eddfffa3f24b54eaf67ea15b7c3b1940fbf87fb73e5f5/lib/github.rb:20:in `block in github_user_orgs'
	from /app/tmp/buildpacks/8bb9ecda5c99fd5b4b98d8c21e7c582252df8a42bc85951aa17af25c483277acf11bfeb81ff44056582eddfffa3f24b54eaf67ea15b7c3b1940fbf87fb73e5f5/lib/github.rb:20:in `each'
	from /app/tmp/buildpacks/8bb9ecda5c99fd5b4b98d8c21e7c582252df8a42bc85951aa17af25c483277acf11bfeb81ff44056582eddfffa3f24b54eaf67ea15b7c3b1940fbf87fb73e5f5/lib/github.rb:20:in `map'
	from /app/tmp/buildpacks/8bb9ecda5c99fd5b4b98d8c21e7c582252df8a42bc85951aa17af25c483277acf11bfeb81ff44056582eddfffa3f24b54eaf67ea15b7c3b1940fbf87fb73e5f5/lib/github.rb:20:in `github_user_orgs'
	from /app/tmp/buildpacks/8bb9ecda5c99fd5b4b98d8c21e7c582252df8a42bc85951aa17af25c483277acf11bfeb81ff44056582eddfffa3f24b54eaf67ea15b7c3b1940fbf87fb73e5f5/lib/github.rb:26:in `user_block'
	from /app/tmp/buildpacks/8bb9ecda5c99fd5b4b98d8c21e7c582252df8a42bc85951aa17af25c483277acf11bfeb81ff44056582eddfffa3f24b54eaf67ea15b7c3b1940fbf87fb73e5f5/bin/compile:54:in `<main>'
 !     Push rejected, failed to compile github-netrc app.
 !     Push failed
```
